### PR TITLE
Analytics

### PR DESCRIPTION
**Pull request by joshpas64**

### CODE REVIEW

**Comment by rohan-achar** [comment]
Please do not merge your submission code into master. Let everyone develop their own solutions to the assignment.

**Comment by rohan-achar** [comment]
Create a pull request ONLY for bug fixes/ feature requests/ enhacements to the common code.

**Comment by joshpas64** [comment]
I'm sorry I meant to merge branch on my own fork. I didn't mean to do it to
the original repo. I'm sorry

**Comment by rohan-achar** [comment]
It's ok. Mistakes happen. 🙂 Carry on.

**Pull request closed without merging**
